### ISSUE TITLE
Build failing due to local fork of pw-rs

### ISSUE THREAD

**Issue by A-Cloud-Ninja** [saivert/pwvucontrol#1]
Hey there, glad to hopefully see a native mixer of some sort soon! I'm trying to build this locally and due to you using a custom pipewire-rs fork, it does not seem like it's currently possible. I've tried using the fork sitting on Gitlab to no avail, as well as mainline.

**Comment by saivert** [comment]
I need to update my pipewire-rs fork. I have forgotten about it.

ons. 14. jun. 2023, 21:16 skrev Matt Mathis ***@***.***>:

**Comment by saivert** [comment]
I have pushed my changes to my pipewire-rs fork and fixed the Cargo.toml in this project so you should be able to build it now.
