### ISSUE TITLE
Change default output device

### ISSUE THREAD

**Issue by jilleJr** [saivert/pwvucontrol#2]
Can I change the default output device from pwvucontrol?

Or is that not a thing in pipewire?

**Comment by saivert** [comment]
It has just not been implemented yet in this application.

You can use pavucontrol (Pulseaudio volume control) or your desktop environment's sound settings to change it or `wptctl` from the command line until pwvucontrol gets this ability

**Comment by saivert** [comment]
This has now been implemented. Will make a release soon.
