### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by revast** [saivert/pwvucontrol#3]
![3us2MaJjra0pnZg_1695288365](https://github.com/saivert/pwvucontrol/assets/8189198/fdc472e0-2bff-4f25-8180-2cd3573fb2d9)

**Comment by saivert** [comment]
Is this your personal work and what is the license?

**Comment by revast** [comment]
its personal, cc-by, was just a try with an AI tool, and I can vectorize it... 

Actually if I think more about it it would probably make more sense to make an icon which can also display the state of the volume slider in (sys)tray/tasklist .. e.g. low mid high volume... like ![image](https://github.com/saivert/pwvucontrol/assets/8189198/76fb248a-784a-49e9-afa8-335a63e0089f)![image](https://github.com/saivert/pwvucontrol/assets/8189198/ac6ff89b-23c5-4003-b453-9dccaca59c81)![image](https://github.com/saivert/pwvucontrol/assets/8189198/702026ef-71b0-4f39-9745-0cebfa8dda5c).

Suggestion:

![pw2](https://github.com/saivert/pwvucontrol/assets/8189198/68b6f315-bf4d-43a1-9451-bbdde1bd1d9c)

In my opinion, it's necessary to provide an actual Icon Set.. to have it look good everywhere (program icon in main window for DE's which support this, Task List, systray, ...), in every size (think 16px!), DarkTheme, LightTheme, Monochrome version - it has to look good in black on white, white on black, should not completely die when gray background... and should be automatically set to the Version according to the Theme applied... loots of variables. 

If your Program has the means to be sort of the default replacement for pavucontrol, it would be nice to have the Icon Set as Vanilla as possible; As to my research, pavucontrol did not have an icon in its sources, it has used the default ones from the chosen icon theme ...

Also, a special icon - in my opinion - would make more sense if you would provide more settings than pavucontrol - pipewire has a lot more things to offer (e.g. Pro audio stuff.. probably best in an Advanced button).

**Comment by saivert** [comment]
Closing as we have a pull request with an actual icon now.

**Comment by revast** [comment]
nice icon and overall progress ;-)
