### ISSUE TITLE
VU-meter's don't move

### ISSUE THREAD

**Issue by Dieterbe** [saivert/pwvucontrol#37]
hello, i just installed https://aur.archlinux.org/packages/pwvucontrol - so the latest git version I guess

I notice that VU-meters don't move. i'm playing music at max volume. VU-meters don't move, not in playback tab, not under output devices, and also not on input devices when i tap onto my microphone (this used to work fine with pavucontrol back when i used pipewire-pulse)

**Comment by Dieterbe** [comment]
strange, now they are working. maybe because i rebooted, or have been changing volumes. not sure.
i'll see if i can reproduce the issue.

**Comment by saivert** [comment]
If they don't move then it means something in the pipewire server went wrong and it was unable to capture audio from the streams/sinks/sources it monitors.
I'm not sure there is much I can do about that from the pwvucontrol side of things. The application simply starts recording from those sources and this must succeed.

**Comment by agvantibo-again** [comment]
VU meters don't move on my NixOS, pwvucontrol 0.4.9

pactl info:
```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 476
Tile Size: 65472
User Name: agvantibo
Host Name: judgement
Server Name: PulseAudio (on PipeWire 1.4.2)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: bluez_output.74_2A_8A_C1_ED_AC.1
Default Source: alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
Cookie: 306e:f85e
```
Log output:
```
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:873: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:905: FINISHME: support more multi-planar formats with DRM modifiers
C 20:52:28.636260        pwvucontrol src/backend/pwdeviceobject.rs:218:: Unable to get model index from profile index.
C 20:52:28.668012        pwvucontrol src/backend/pwdeviceobject.rs:218:: Unable to get model index from profile index.
```
