### ISSUE TITLE
What are the differences between this app and pavucontrol?

### ISSUE THREAD

**Issue by dougg0k** [saivert/pwvucontrol#40]
Hi,

The title.

**Comment by jujudusud** [comment]
Pavucontrol is using PulseAudio's API while pwvucontrol is using PipeWire's and WirePlumber's.

**Comment by dougg0k** [comment]
I have only pipewire installed and pavucontrol gives the same options and it is said that it works with pipewire too. Not sure if due to pipewire-pulse.

**Comment by dougg0k** [comment]
Yeah, I am no longer using pavu, it's replaced with this tool.
