### ISSUE TITLE
Crash when setting profile "pw_property media.class not found"

### ISSUE THREAD

**Issue by SWW13** [saivert/pwvucontrol#50]
When I change the profile of my headset (JBL Quantum810) to ProAudio `pwvucontrol` crashes:

```
pwvucontrol src/ui/profile_dropdown.rs:165:: Setting profile to dropdown index = 5 profile index = 5
thread 'main' panicked at src/backend/pwnodeobject.rs:618:36:
media.class: Error { domain: wireplumber-library, code: 1, message: "pw_property media.class not found" }
```

When some applications start the profile changes "on it's own" which also crashes `pwvucontrol`. I'm trying to fix that, but that's another topic unrelated to `pwvucontrol`.

I'm running version `0.4.6` from AUR (arch linux user repository). The backtrace of this release build is useless, if needed I can create one with a debug build.

**Comment by saivert** [comment]
Released 0.4.7 which fixes this. Coming soon to Flathub.
